class Config:
    FPS = 60
    INITIAL_SCREEN_SIZE = (1024, 576)

    SPEED_OPTIONS = [1, 2, 4]

    GAME_OVER_QUOTES = ("TJA...", "HMMMMMMMMMMM", "CLOSE", "NEVER GIVE UP", "YOU DID GREAT!", "YOU'VE GOT THIS")
    WIN_CELEBRATION_QUOTES = ("GG EZ", "GG WP!", "TOO EASY...", "YOU DID IT!")

    ENEMY_SPEED = 50

    SKIP_INTRO = False
